WIP #4
go-generalize/repo_generator pull request #6
Opened 2020-05-07 06:44 UTC by 54mch4n

2020-05-12 09:23 UTC, moezakura requested changes
いくつかコメントしました。

2020-05-12 09:23 UTC, moezakura commented on emulator_test.go
> +		fmt.Print("Failure pattern -> ")
t.Log で表示したほうがいいかと思います。

2020-05-12 09:23 UTC, moezakura commented on main.go
>  func generate(gen *generator, fs *token.FileSet, structType *ast.StructType) error {
この関数めちゃくちゃ長いので分けたほうがいいかもしれません。

2020-05-12 10:01 UTC, 54mch4n commented on emulator_test.go
> +		fmt.Print("Failure pattern -> ")
これは意図時で、`go test -tags emulator` だと ただ 
```
2020/05/12 18:58:25 task.go:21:2: the type of `Flag` is an invalid type in struct `Task` [Flag]
```
 となってしまうため、実行者からしたらエラー出てるじゃん！ってなりかねず。
それと、`go test -v -tags emulator` をして出力させたとしても
t.Logだと改行されてしまうのでfmt.Printにしました

2020-05-12 10:12 UTC, moezakura commented on emulator_test.go
> +		fmt.Print("Failure pattern -> ")
なるほど、そうしたらコメントで書いてもらえるとわかりやすいです。

2020-05-12 10:17 UTC, 54mch4n commented on main.go
>  func generate(gen *generator, fs *token.FileSet, structType *ast.StructType) error {
[f61e3cf](https://github.com/go-generalize/repo_generator/pull/6/commits/f61e3cf51d27d63359bf8447cfd31a2616d64dfa)で対応

2020-05-12 10:23 UTC, 54mch4n commented on emulator_test.go
> +		fmt.Print("Failure pattern -> ")
[d01f887](https://github.com/go-generalize/repo_generator/pull/6/commits/d01f8870e4c5f18b3044e969f1575da9017b77b7)で対応

2020-05-12 10:26 UTC, moezakura approved these changes
LGTM

2020-05-14 02:20 UTC, tsuzu reviewed
一点だけ確認お願いしたいです 🙇

2020-05-14 02:20 UTC, cs3238-tsuzu commented on .gitignore
> +go.sum
https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

go.sumはGoの公式で基本的にcommitした方が良いらしいのですがignoreしているのは何か問題がありそうですか?

2020-05-14 03:27 UTC, 54mch4n commented on .gitignore
> +go.sum
一応[メモ](https://twitter.com/ymmt2005/status/1095266743046393856)
```
現時点では Go modules の go.sum ファイルは git add しないほうがいい。
go.sum のチェックサム計算方法はたびたび変わってるのだけど、
計算方法のバージョン管理がないものだから全開発者が Go のバージョン
をきっちり揃えないと checksum mismatch で死ねる。
```

2020-05-14 03:40 UTC, 54mch4n commented on .gitignore
> +go.sum
大丈夫そうとのことで戻す
[メモ](https://github.com/golang/go/issues/30369)

2020-05-14 03:40 UTC, 54mch4n commented on .gitignore
> +go.sum
[9a98767](https://github.com/go-generalize/repo_generator/pull/6/commits/9a98767c392d17f50aad5e3f94e51d37885cb4c4)で対応

2020-05-14 03:50 UTC, tsuzu approved these changes
LGTM! 🎉 
Thanks

2020-05-14 03:50 UTC, merged